# Generated by Django 6.0.2 on 2026-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
